# Generated by Django 6.1.1 on 2026-09-23 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message from tenant to property owner detailing move-in date, occupancy, or questions.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the rental request.', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The requested property.', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='properties.property')),
                ('tenant', models.ForeignKey(help_text='The tenant sending the request.', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('property', 'tenant'), name='unique_pending_request_per_tenant_property')],
            },
        ),
    ]
