# Generated by Django 6.1.1 on 2026-09-23 05:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property listing headline or title.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the property, features, and lease terms.')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('ROOM', 'Room'), ('OFFICE', 'Office')], default='APARTMENT', help_text='Type of property.', max_length=20)),
                ('location', models.CharField(help_text='City, neighborhood, or full address.', max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rental price in USD / BDT.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bedrooms', models.PositiveIntegerField(default=1, help_text='Number of bedrooms (0 for studio/office).', validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.PositiveIntegerField(default=1, help_text='Number of bathrooms.', validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, help_text='Main photo of the property.', null=True, upload_to='property_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Mark whether the property is currently available for rent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The property owner who manages this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
